# middleware.py — middleware repo clone, config generation, systemd service setup

import os
import platform
import shutil
import subprocess
import sys
import tempfile

from .constants import C, MIDDLEWARE_DIR, MIDDLEWARE_REPO
from .ui import ask_yesno


def generate_config(scanner_config: dict, middleware_config: dict) -> str:
    """Generate middleware config.yaml from collected settings."""
    # Scanner device ID maps to action type; action determines MQTT→Klipper behavior
    scanners = middleware_config.get("scanners", [])
    scanner_lines: list[str] = []
    for i, s in enumerate(scanners):
        # Placeholder until scanner is flashed and MQTT topic is available
        device_id = f"YOUR_DEVICE_ID_{i + 1}" if len(scanners) > 1 else "YOUR_DEVICE_ID"
        scanner_lines.append(f'  "{device_id}":')
        scanner_lines.append(f'    action: "{s["action"]}"')
        # Lane/toolhead parameters route scan events to specific AFC lane or toolhead
        if "lane" in s:
            scanner_lines.append(f'    lane: "{s["lane"]}"')
        if "toolhead" in s:
            scanner_lines.append(f'    toolhead: "{s["toolhead"]}"')
    scanners_yaml = "\n".join(scanner_lines)

    # low_spool_threshold triggers alerts when filament falls below grams threshold
    config_yaml = f"""# Generated by SpoolSense Installer
# https://github.com/SpoolSense/spoolsense-installer
#
# After flashing your scanner(s), find each device ID from MQTT:
#   spoolsense/<device_id>/tag/state
# Replace YOUR_DEVICE_ID below with the actual device ID.

mqtt:
  broker: "{scanner_config['mqtt_host']}"
  port: {scanner_config['mqtt_port']}
  username: "{scanner_config['mqtt_user']}"
  password: "{scanner_config['mqtt_pass']}"

spoolman_url: "{scanner_config['spoolman_url']}"

moonraker_url: "{middleware_config['moonraker_url']}"

low_spool_threshold: 100

# Must match the scanner firmware's compile-time MQTT topic prefix
scanner_topic_prefix: "spoolsense"

scanners:
{scanners_yaml}

# Slicer integration — publish spool data to Moonraker's lane_data database
publish_lane_data: {str(middleware_config.get('publish_lane_data', False)).lower()}
"""
    return config_yaml


# Which shipped macro files each setup type needs. spoolsense.cfg carries
# ASSIGN_SPOOL/UPDATE_TAG — UPDATE_TAG drives filament deduction in every mode.
# spoolman_macros.cfg (SET_ACTIVE_SPOOL) is for direct-toolhead setups; AFC
# manages its own Spoolman state. toolhead_macros_example.cfg is a per-tool
# template for multi-tool setups.
_MACROS_BY_SETUP = {
    "spoolsense.cfg": ("afc_stage", "afc_lane", "toolhead_stage", "toolchanger", "single"),
    "spoolman_macros.cfg": ("toolhead_stage", "toolchanger", "single"),
    "toolhead_macros_example.cfg": ("toolhead_stage", "toolchanger"),
}
# spoolsense.cfg is SpoolSense-owned and safe to refresh; the others are
# templates the user edits, so an existing copy is never touched.
_REFRESH_ON_REINSTALL = ("spoolsense.cfg",)


def copy_klipper_macros(setup_type: str, src_dir: str = None, dst_dir: str = None) -> dict:
    """Copy the Klipper macro files this setup type needs into the printer config dir.

    Returns {filename: status} with status one of "copied", "kept-existing",
    "missing-source". Missing sources are reported, not fatal — the middleware
    checkout may predate a macro file.
    """
    if src_dir is None:
        src_dir = os.path.join(MIDDLEWARE_DIR, "middleware", "klipper")
    if dst_dir is None:
        dst_dir = os.path.expanduser("~/printer_data/config")

    results = {}
    for name, setup_types in _MACROS_BY_SETUP.items():
        if setup_type not in setup_types:
            continue
        src = os.path.join(src_dir, name)
        dst = os.path.join(dst_dir, name)
        if not os.path.exists(src):
            results[name] = "missing-source"
            continue
        if os.path.exists(dst) and name not in _REFRESH_ON_REINSTALL:
            results[name] = "kept-existing"
            continue
        shutil.copy2(src, dst)
        results[name] = "copied"
    return results


def install(config_yaml: str) -> dict:
    """Clone SpoolSense middleware, install deps, write config, create service.

    Returns step outcomes: {"config": "written"|"kept", "service": True|False|None}
    (service None = not attempted, e.g. non-Linux host). Fatal failures still
    exit directly.
    """
    print(f"\n{C.CYAN}── Installing Middleware ────────────────{C.RESET}\n")

    if os.path.isdir(MIDDLEWARE_DIR):
        print("  SpoolSense middleware directory exists, updating...")
        subprocess.run(["git", "-C", MIDDLEWARE_DIR, "pull", "--quiet"], check=True)
    else:
        print("  Cloning SpoolSense middleware...")
        subprocess.run(["git", "clone", "--quiet", MIDDLEWARE_REPO, MIDDLEWARE_DIR], check=True)
    print("  ✓ Repository ready")

    print("  Installing Python dependencies...")
    req_file = os.path.join(MIDDLEWARE_DIR, "middleware", "requirements.txt")
    if not os.path.exists(req_file):
        print(f"  {C.RED}✗ requirements.txt not found at {req_file}{C.RESET}")
        print("    The middleware repository may be incomplete. Try deleting")
        print(f"    {MIDDLEWARE_DIR} and running the installer again.")
        sys.exit(1)

    try:
        # --break-system-packages needed on Debian bookworm; 5min timeout for large dependency trees
        result = subprocess.run([sys.executable, "-m", "pip", "install", "--quiet",
                                 "--break-system-packages", "-r", req_file],
                                capture_output=True, text=True, timeout=300)
    except subprocess.TimeoutExpired:
        print(f"  {C.RED}✗ pip install timed out after 5 minutes{C.RESET}")
        print(f"    Try manually: pip3 install -r {req_file}")
        sys.exit(1)

    if result.returncode != 0:
        print(f"  {C.RED}✗ Failed to install Python dependencies{C.RESET}")
        output = result.stderr.strip() if result.stderr else result.stdout.strip()
        if output:
            print(f"    {output}")
        print(f"    Try manually: pip3 install -r {req_file}")
        sys.exit(1)
    print("  ✓ Dependencies installed")

    # Config lives in SpoolSense root directory
    config_status = "written"
    config_path = os.path.join(MIDDLEWARE_DIR, "config.yaml")
    if os.path.exists(config_path):
        print(f"  ⚠  Existing config found at {config_path}")
        if not ask_yesno("  Overwrite?", default=False):
            print("  Keeping existing config.")
            config_status = "kept"
    if config_status == "written":
        with open(config_path, "w") as f:
            f.write(config_yaml)
        print(f"  {C.GREEN}✓{C.RESET} Config written to {config_path}")

    service_status = None
    if platform.system() == "Linux" and shutil.which("systemctl"):
        service_status = create_systemd_service()

    return {"config": config_status, "service": service_status}


def create_systemd_service() -> bool:
    """Create and enable systemd service for SpoolSense middleware."""
    # After=network-online.target ensures MQTT broker is reachable before starting
    service_content = f"""[Unit]
Description=SpoolSense Middleware
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
User={os.environ.get('USER', 'pi')}
WorkingDirectory={MIDDLEWARE_DIR}/middleware
ExecStart={sys.executable} {MIDDLEWARE_DIR}/middleware/spoolsense.py
Restart=on-failure
RestartSec=5

[Install]
WantedBy=multi-user.target
"""
    service_path = "/etc/systemd/system/spoolsense.service"
    tmp_path = os.path.join(tempfile.gettempdir(), "spoolsense.service")

    with open(tmp_path, "w") as f:
        f.write(service_content)

    print("  Creating systemd service...")
    try:
        subprocess.run(["sudo", "cp", tmp_path, service_path], check=True)
        subprocess.run(["sudo", "systemctl", "daemon-reload"], check=True)
        # enable creates symlink for automatic restart on boot
        subprocess.run(["sudo", "systemctl", "enable", "spoolsense"], check=True)
        subprocess.run(["sudo", "systemctl", "restart", "spoolsense"], check=True)
        print("  ✓ SpoolSense service started and enabled on boot")
        os.unlink(tmp_path)
        return True
    except subprocess.CalledProcessError:
        # Keep the tmp file — the manual-setup instruction points at it.
        print(f"{C.YELLOW}  ⚠ {C.RESET} Could not create systemd service (requires sudo)")
        print(f"     Manual setup: copy {tmp_path} to {service_path}")
        return False
