# middleware.py — middleware repo clone, config generation, systemd service setup

import json
import os
import platform
import re
import shutil
import subprocess
import sys
import tempfile
import urllib.request

from .constants import C, MIDDLEWARE_DIR, MIDDLEWARE_RELEASE_API, MIDDLEWARE_REPO, MOONRAKER_CONF_PATH
from .ui import ask_yesno
from .errors import InstallerError
from .files import backup_file


def generate_config(scanner_config: dict, middleware_config: dict) -> str:
    """Generate middleware config.yaml from collected settings."""
    # Scanner device ID maps to action type; action determines MQTT→Klipper behavior
    scanners = middleware_config.get("scanners", [])
    scanner_lines: list[str] = []
    for i, s in enumerate(scanners):
        # Placeholder until scanner is flashed and MQTT topic is available
        device_id = f"YOUR_DEVICE_ID_{i + 1}" if len(scanners) > 1 else "YOUR_DEVICE_ID"
        scanner_lines.append(f'  "{device_id}":')
        scanner_lines.append(f'    action: "{s["action"]}"')
        # Lane/toolhead parameters route scan events to specific AFC lane or toolhead
        if "lane" in s:
            scanner_lines.append(f'    lane: "{s["lane"]}"')
        if "toolhead" in s:
            scanner_lines.append(f'    toolhead: "{s["toolhead"]}"')
    scanners_yaml = "\n".join(scanner_lines)

    setup_type = middleware_config.get("setup_type", "")

    # Happy Hare pull-mode binding (middleware v1.7.3+) needs its own section;
    # the middleware refuses to bind without enabled + printer_name.
    happy_hare_yaml = ""
    if setup_type == "happy_hare":
        happy_hare_yaml = f"""
# Happy Hare MMU integration — requires pull mode and the mmu_gate /
# printer_name extra fields in Spoolman (the installer creates them).
happy_hare:
  enabled: true
  printer_name: "{middleware_config.get('printer_name', '')}"
"""

    # Explicit toolheads list (issue #24) — the mobile app picker reads it;
    # without it, shared-scanner setups fall back to hardcoded defaults.
    toolheads_yaml = ""
    toolheads = middleware_config.get("toolheads") or []
    if toolheads:
        entries = "\n".join(f'  - "{t}"' for t in toolheads)
        toolheads_yaml = f"\ntoolheads:\n{entries}\n"

    # Web config panel / mobile REST API (middleware v1.7.0+, port 5001)
    mobile_yaml = ""
    if middleware_config.get("mobile_enabled"):
        if setup_type in ("afc_stage", "afc_lane"):
            mobile_action_lines = '  action: "afc_stage"'
        elif setup_type == "toolhead_stage":
            mobile_action_lines = '  action: "toolhead_stage"'
        else:
            first_toolhead = toolheads[0] if toolheads else "T0"
            mobile_action_lines = f'  action: "toolhead"\n  toolhead: "{first_toolhead}"'
        mobile_yaml = f"""
# Web config panel + mobile REST API — http://<printer-host>:5001
mobile:
  enabled: true
{mobile_action_lines}
  port: 5001
"""

    # low_spool_threshold triggers alerts when filament falls below grams threshold
    low_spool = middleware_config.get("low_spool_threshold", 100)

    config_yaml = f"""# Generated by SpoolSense Installer
# https://github.com/SpoolSense/spoolsense-installer
#
# After flashing your scanner(s), find each device ID from MQTT:
#   spoolsense/<device_id>/tag/state
# Replace YOUR_DEVICE_ID below with the actual device ID.

mqtt:
  broker: "{scanner_config['mqtt_host']}"
  port: {scanner_config['mqtt_port']}
  username: "{scanner_config['mqtt_user']}"
  password: "{scanner_config['mqtt_pass']}"

spoolman_url: "{scanner_config['spoolman_url']}"

moonraker_url: "{middleware_config['moonraker_url']}"

low_spool_threshold: {low_spool}

# Must match the scanner firmware's compile-time MQTT topic prefix
scanner_topic_prefix: "spoolsense"
{happy_hare_yaml}
scanners:
{scanners_yaml}
{toolheads_yaml}{mobile_yaml}
# Slicer integration — publish spool data to Moonraker's lane_data database
publish_lane_data: {str(middleware_config.get('publish_lane_data', False)).lower()}
"""
    return config_yaml


# Which shipped macro files each setup type needs. spoolsense.cfg carries
# ASSIGN_SPOOL/UPDATE_TAG — UPDATE_TAG drives filament deduction in every mode.
# spoolman_macros.cfg (SET_ACTIVE_SPOOL) is for direct-toolhead setups; AFC
# manages its own Spoolman state. toolhead_macros_example.cfg is a per-tool
# template for multi-tool setups.
_MACROS_BY_SETUP = {
    "spoolsense.cfg": ("afc_stage", "afc_lane", "toolhead_stage", "toolchanger", "single",
                       "happy_hare"),
    "spoolman_macros.cfg": ("toolhead_stage", "toolchanger", "single"),
    "toolhead_macros_example.cfg": ("toolhead_stage", "toolchanger"),
}
# spoolsense.cfg is SpoolSense-owned and safe to refresh; the others are
# templates the user edits, so an existing copy is never touched.
_REFRESH_ON_REINSTALL = ("spoolsense.cfg",)


def copy_klipper_macros(setup_type: str, src_dir: str = None, dst_dir: str = None) -> dict:
    """Copy the Klipper macro files this setup type needs into the printer config dir.

    Returns {filename: status} with status one of "copied", "kept-existing",
    "missing-source". Missing sources are reported, not fatal — the middleware
    checkout may predate a macro file.
    """
    if src_dir is None:
        src_dir = os.path.join(MIDDLEWARE_DIR, "middleware", "klipper")
    if dst_dir is None:
        dst_dir = os.path.expanduser("~/printer_data/config")

    results = {}
    for name, setup_types in _MACROS_BY_SETUP.items():
        if setup_type not in setup_types:
            continue
        src = os.path.join(src_dir, name)
        dst = os.path.join(dst_dir, name)
        if not os.path.exists(src):
            results[name] = "missing-source"
            continue
        if os.path.exists(dst) and name not in _REFRESH_ON_REINSTALL:
            results[name] = "kept-existing"
            continue
        shutil.copy2(src, dst)
        results[name] = "copied"
    return results


def latest_release_tag() -> str:
    """Latest middleware release tag from GitHub, or None if unavailable."""
    try:
        req = urllib.request.Request(MIDDLEWARE_RELEASE_API,
                                     headers={"Accept": "application/vnd.github.v3+json"})
        with urllib.request.urlopen(req, timeout=15) as resp:
            return json.loads(resp.read().decode()).get("tag_name") or None
    except Exception:  # noqa: BLE001 — pinning is best-effort; fall back to branch head
        return None


def pin_repo_to_release(repo_dir: str, tag: str) -> bool:
    """Move a clean checkout to the given release tag, staying on master.

    Users get the latest *release* instead of whatever is on branch head, and
    Moonraker's update_manager (channel: stable) takes over from there. Only
    moves when HEAD == origin/master — never discards local commits.
    """
    def rev(ref):
        r = subprocess.run(["git", "-C", repo_dir, "rev-parse", "--verify", ref],
                           capture_output=True, text=True)
        return r.stdout.strip() if r.returncode == 0 else None

    tag_sha, head, upstream = rev(f"{tag}^{{commit}}"), rev("HEAD"), rev("origin/master")
    if not tag_sha:
        print(f"  {C.YELLOW}!{C.RESET} Release tag {tag} not found in clone — using branch head")
        return False
    status = subprocess.run(["git", "-C", repo_dir, "status", "--porcelain"],
                            capture_output=True, text=True)
    dirty = status.returncode != 0 or bool(status.stdout.strip())
    if head != upstream or dirty:
        print(f"  {C.YELLOW}!{C.RESET} Local changes detected in {repo_dir} — not pinning to {tag}")
        return False
    # reset (not checkout) keeps us on the master branch, which Moonraker's
    # update_manager requires
    result = subprocess.run(["git", "-C", repo_dir, "reset", "--hard", "--quiet", tag_sha])
    return result.returncode == 0


def venv_python(venv_dir: str) -> str:
    """Path to the python interpreter inside a venv (platform-aware)."""
    if platform.system() == "Windows":
        return os.path.join(venv_dir, "Scripts", "python.exe")
    return os.path.join(venv_dir, "bin", "python")


def ensure_venv(venv_dir: str) -> str:
    """Create the venv if missing; return its python path.

    Isolates middleware deps from the system interpreter — no more
    --break-system-packages on Debian Bookworm (#21).
    """
    python = venv_python(venv_dir)
    if os.path.exists(python):
        return python

    print(f"  Creating virtual environment at {venv_dir}...")
    result = subprocess.run([sys.executable, "-m", "venv", venv_dir],
                            capture_output=True, text=True)
    if result.returncode != 0 or not os.path.exists(python):
        print(f"  {C.RED}✗ Could not create a virtual environment{C.RESET}")
        err = (result.stderr or result.stdout).strip()
        if err:
            print(f"    {err.splitlines()[-1]}")
        print("    On Raspberry Pi / Debian: sudo apt install python3-venv")
        raise InstallerError
    return python


def install(config_yaml: str, dev: bool = False) -> dict:
    """Clone SpoolSense middleware, install deps, write config, create service.

    Pins the checkout to the latest release tag unless ``dev`` is set.
    Returns step outcomes: {"config": "written"|"kept", "service": True|False|None,
    "pinned": tag-or-None}. Fatal failures still exit directly.
    """
    print(f"\n{C.CYAN}── Installing Middleware ────────────────{C.RESET}\n")

    if os.path.isdir(MIDDLEWARE_DIR):
        print("  SpoolSense middleware directory exists, updating...")
        subprocess.run(["git", "-C", MIDDLEWARE_DIR, "pull", "--quiet"], check=True)
    else:
        print("  Cloning SpoolSense middleware...")
        subprocess.run(["git", "clone", "--quiet", MIDDLEWARE_REPO, MIDDLEWARE_DIR], check=True)

    pinned = None
    if not dev:
        tag = latest_release_tag()
        if tag and pin_repo_to_release(MIDDLEWARE_DIR, tag):
            pinned = tag
            print(f"  ✓ Repository ready (release {tag})")
        else:
            print("  ✓ Repository ready (branch head)")
    else:
        print("  ✓ Repository ready (dev mode — branch head)")

    print("  Installing Python dependencies (this can take a few minutes)...")
    req_file = os.path.join(MIDDLEWARE_DIR, "middleware", "requirements.txt")
    if not os.path.exists(req_file):
        print(f"  {C.RED}✗ requirements.txt not found at {req_file}{C.RESET}")
        print("    The middleware repository may be incomplete. Try deleting")
        print(f"    {MIDDLEWARE_DIR} and running the installer again.")
        raise InstallerError

    # Deps live in the middleware's own venv (#21) — never the system python
    python = ensure_venv(os.path.join(MIDDLEWARE_DIR, ".venv"))
    try:
        # 5min timeout for large dependency trees; output streams so the
        # user sees progress.
        result = subprocess.run([python, "-m", "pip", "install", "-r", req_file],
                                timeout=300)
    except subprocess.TimeoutExpired:
        print(f"  {C.RED}✗ pip install timed out after 5 minutes{C.RESET}")
        print(f"    Try manually: {python} -m pip install -r {req_file}")
        raise InstallerError

    if result.returncode != 0:
        print(f"  {C.RED}✗ Failed to install Python dependencies{C.RESET}")
        print(f"    Try manually: {python} -m pip install -r {req_file}")
        raise InstallerError
    print("  ✓ Dependencies installed")

    # Config lives in SpoolSense root directory
    config_status = "written"
    config_path = os.path.join(MIDDLEWARE_DIR, "config.yaml")
    if os.path.exists(config_path):
        print(f"  ⚠  Existing config found at {config_path}")
        if not ask_yesno("  Overwrite?", default=False):
            print("  Keeping existing config.")
            config_status = "kept"
    if config_status == "written":
        bak = backup_file(config_path)
        if bak:
            print(f"  {C.DIM}Backed up existing config to {bak}{C.RESET}")
        with open(config_path, "w") as f:
            f.write(config_yaml)
        print(f"  {C.GREEN}✓{C.RESET} Config written to {config_path}")

    service_status = None
    if platform.system() == "Linux" and shutil.which("systemctl"):
        service_status = create_systemd_service(python)

    return {"config": config_status, "service": service_status, "pinned": pinned}


def setup_moonraker_update_manager(conf_path: str = None) -> str:
    """Offer to add [update_manager spoolsense] to moonraker.conf (#16).

    Gives users an update button in Mainsail/Fluidd. channel: stable keeps
    them on tagged releases (matches the installer pinning the clone to the
    latest release); Moonraker restarts the service after each update.

    Returns one of: "added", "exists", "declined", "missing-conf", "failed".
    """
    if conf_path is None:
        conf_path = MOONRAKER_CONF_PATH

    # virtualenv/requirements let Moonraker update python deps with the repo
    block = f"""
[update_manager spoolsense]
type: git_repo
channel: stable
path: {MIDDLEWARE_DIR}
origin: {MIDDLEWARE_REPO}
primary_branch: master
virtualenv: {MIDDLEWARE_DIR}/.venv
requirements: middleware/requirements.txt
managed_services: spoolsense
"""

    if not os.path.exists(conf_path):
        print(f"  {C.YELLOW}!{C.RESET} moonraker.conf not found at {conf_path}")
        print("    To get SpoolSense updates in Mainsail/Fluidd, add this manually:")
        print(block)
        return "missing-conf"

    with open(conf_path, "r") as f:
        content = f.read()

    if re.search(r"^\[update_manager spoolsense\]\s*$", content, re.MULTILINE):
        print(f"  {C.GREEN}✓{C.RESET} Moonraker update_manager entry already exists — skipping")
        return "exists"

    print(f"\n  {C.YELLOW}Mainsail/Fluidd updates:{C.RESET} Moonraker's update manager can show")
    print("  SpoolSense middleware updates in the web UI and install them")
    print("  with one click (stable releases only).\n")

    if not ask_yesno("Add [update_manager spoolsense] to moonraker.conf?", default=True):
        print("  Skipped. You can add it manually later.")
        return "declined"

    try:
        backup_file(conf_path)
        with open(conf_path, "a") as f:
            f.write(block)
        print(f"  {C.GREEN}✓{C.RESET} Added [update_manager spoolsense] to {conf_path}")
        print(f"  {C.YELLOW}Important:{C.RESET} restart Moonraker for this to take effect.")
        return "added"
    except Exception as e:  # noqa: BLE001
        print(f"  {C.RED}✗{C.RESET} Failed to write moonraker.conf: {e}")
        return "failed"


def service_content(python_path: str) -> str:
    """The spoolsense.service systemd unit, running with the given python.

    After=network-online.target ensures the MQTT broker is reachable before
    starting.
    """
    return f"""[Unit]
Description=SpoolSense Middleware
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
User={os.environ.get('USER', 'pi')}
WorkingDirectory={MIDDLEWARE_DIR}/middleware
ExecStart={python_path} {MIDDLEWARE_DIR}/middleware/spoolsense.py
Restart=on-failure
RestartSec=5

[Install]
WantedBy=multi-user.target
"""


def create_systemd_service(python_path: str = None) -> bool:
    """Create and enable systemd service for SpoolSense middleware."""
    if python_path is None:
        python_path = venv_python(os.path.join(MIDDLEWARE_DIR, ".venv"))
    unit_text = service_content(python_path)
    service_path = "/etc/systemd/system/spoolsense.service"
    tmp_path = os.path.join(tempfile.gettempdir(), "spoolsense.service")

    with open(tmp_path, "w") as f:
        f.write(unit_text)

    print("  Creating systemd service...")
    try:
        subprocess.run(["sudo", "cp", tmp_path, service_path], check=True)
        subprocess.run(["sudo", "systemctl", "daemon-reload"], check=True)
        # enable creates symlink for automatic restart on boot
        subprocess.run(["sudo", "systemctl", "enable", "spoolsense"], check=True)
        subprocess.run(["sudo", "systemctl", "restart", "spoolsense"], check=True)
        print("  ✓ SpoolSense service started and enabled on boot")
        os.unlink(tmp_path)
        return True
    except subprocess.CalledProcessError:
        # Keep the tmp file — the manual-setup instruction points at it.
        print(f"{C.YELLOW}  ⚠ {C.RESET} Could not create systemd service (requires sudo)")
        print(f"     Manual setup: copy {tmp_path} to {service_path}")
        return False
